mysql:
  charset: utf8
  db: sample
  host: 127.0.0.1
  password: jason0918
  user: root
mail:
  smtp: smtp.qq.com
  smtp-port: 587
  user: 136766316@qq.com
  password: nyomfoisumnjcaif
server:
    url: http://127.0.0.1:8888